type Q = (sql: string, params?: unknown[]) => Promise<any[]>;
export type 후보 = { 키: string; 제목: string; 신호: string[]; 이유: string; 점수: number; 학원사실필요: boolean; 분류?: string; 각도?: string; 태그?: string[]; 경쟁출처?: string[] };
export type 주장 = { 문장: string; 숫자: string[]; 고유명사: string[]; 제도어: string[]; 빌린말?: { 고유명사: string[]; 제도어: string[] } };
export type 라벨재료 = { 라벨: string; 원문: string; id?: string; 날?: string; 연도?: number; slug?: string };
export type 기록행 = { kind: string; slug?: string | null; attempt?: number | null; passed?: boolean | null; why?: string | null; at: string | Date; topic_key?: string };
export const KST날: (t?: number) => string;
export const KST월일: (t: number | string | Date) => string;
export function 주시작(now?: number): number;
export function 주제키(c: { bank?: string; 질문?: string; 검색어?: string }): string;
export function 학원사실필요(제목: string, 분류?: string): boolean;
export const 철: Record<string, number[]>;
export function 후보모으기(q: Q, o?: { client?: number; 은행?: any[]; now?: number }): Promise<{ 후보: 후보[]; 못읽음: string[] }>;
export const STOP: Set<string>;
export const 낱말: (s: string) => string[];
export function 거르기(후보들: 후보[], 기록?: { topic_key: string; kind: string; at: string | Date }[], 최근글?: { title: string; tags?: string[]; published_at: string | Date }[], o?: { now?: number; 모든제목?: string[] }): { 남은것: 후보[]; 뺀것: { 제목: string; 왜: string }[] };
export function 재료모으기(q: Q, client?: number): Promise<{ m: 라벨재료[]; i: 라벨재료[]; p: 라벨재료[] }>;
export function 재료판정(후보: Partial<후보>, 라벨들: { m?: unknown[]; i?: unknown[]; p?: unknown[] }): { 결과: "재료부족" | "재료" | "사실"; 왜: string };
export const 이번주글SQL: string;
export function 접기(s: string): { 글: string; 자리: number[]; src: string };
export function 주장뽑기(body: string): 주장[];
export function 창찾기(원문: string, 주장: Partial<주장>): string[];
export function JSON꺼내기(text: string): any;
export function 판정읽기(text: string, 대상: { id: string; 창들: string[] }[]): Map<string, { 판정: "맞음" | "다름" | "없음"; 근거: string; 왜?: string }>;
export function 문장지우기(body: string, 문장들: string[]): { body: string; 지운것: string[]; 첫문단지움: boolean };
export function 본문해시(body: string): string;
export function 다듬기검사(전: string, 후: string): string | null;
export function 다음행동(o?: { 회차?: number; 결과?: string; 오늘감수있음?: boolean }): "통과" | "내일다시" | "버림" | "미룸";
export function 관점읽기(text: string, body: string): { 통과: boolean; 걸림: { 문장: string; 종류: string }[]; 버린걸림: { 문장: string; 종류: string }[]; 말리기: string; 왜: string };
export function 글기록말(rows?: 기록행[], now?: number): string | null;
export function 글기록읽기(q: Q, client?: number): Promise<string | null>;
export const 기록하기: (q: Q, r: { client?: number; slug?: string | null; topic_key: string; kind: string; attempt?: number | null; passed?: boolean | null; stages?: unknown; why?: string | null }) => Promise<any[]>;
export function 자동발행켜짐(q: Q): Promise<boolean>;
export function 발행가능(q: Q, slug: string, o?: { 자동?: boolean }): Promise<{ ok: boolean; 왜: string }>;
export function 발행(q: Q, slug: string, o?: { 누가?: "원장" | "자동" }): Promise<{ ok: boolean; title?: string; clientId?: number }>;
export function 내리기(q: Q, slug: string, o?: { 이유?: string; 블로그?: string; now?: number }): Promise<{ ok: boolean; title?: string }>;
export function 버리기(q: Q, slug: string, o?: { 왜?: string }): Promise<{ ok: boolean; title?: string }>;
