import { redirect } from "next/navigation";
import Link from "next/link";
import { isAdmin } from "@/lib/admin-auth";
import { listOutreach, OUTREACH_STATUSES } from "@/lib/outreach";
import { updateOutreach } from "@/lib/outreach-actions";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";
const HERE = "/admin/outreach";

const yn = (v: boolean | null) => v === true ? "yes" : v === false ? "no" : "unknown";
const qualifies = (t: Awaited<ReturnType<typeof listOutreach>>[number]) =>
  t.ownerConsults === true && t.monthlyInquiries5plus === true && t.singleLocation === true;

const CSS = `
.out{--bg:#0c1016;--card:#151b23;--line:#28313d;--ink:#edf1f5;--mut:#9aa5b3;--faint:#667180;--acc:#f5a623;--ok:#3dd6a0;--bad:#d2705f;background:var(--bg);color:var(--ink);min-height:100vh;padding:36px 0 90px;font-family:"Noto Sans KR",system-ui,sans-serif}.out *{box-sizing:border-box}.out .w{max-width:1180px;margin:auto;padding:0 24px}.out a{color:inherit}.top{display:flex;justify-content:space-between;gap:20px;align-items:end;border-bottom:1px solid var(--line);padding-bottom:20px}.eyebrow{font-size:11px;letter-spacing:.18em;color:var(--acc);font-weight:800}.out h1{font-size:28px;margin:7px 0 4px;letter-spacing:-.04em}.desc{color:var(--mut);font-size:13px}.back{font-size:13px;color:var(--mut)!important}.score{display:grid;grid-template-columns:repeat(5,1fr);gap:9px;margin:18px 0}.score div{border:1px solid var(--line);background:var(--card);border-radius:12px;padding:14px}.score b{font-size:25px;display:block}.score span{font-size:12px;color:var(--mut)}.today{border:1px solid #5b451e;background:#1b1710;border-radius:14px;padding:20px;margin:24px 0}.today h2{font-size:18px;margin:0 0 13px}.today ol{margin:0;padding-left:22px;line-height:1.85;font-size:14px}.today strong{color:var(--acc)}.script{border-top:1px solid #40331e;margin-top:14px;padding-top:14px;color:#d7c7a8;font-size:13px;line-height:1.7}.cards{display:grid;gap:12px}.card{border:1px solid var(--line);background:var(--card);border-radius:14px;padding:18px}.head{display:flex;justify-content:space-between;gap:14px}.rank{font:12px ui-monospace;color:var(--acc);margin-right:8px}.name{font-size:17px;font-weight:800}.meta{color:var(--mut);font-size:12.5px;margin-top:5px}.links{display:flex;gap:10px;font-size:12px;color:#76daca;margin-top:8px}.flag{font-size:11px;padding:4px 8px;border:1px solid var(--line);border-radius:999px;color:var(--mut);white-space:nowrap}.flag.ok{color:var(--ok);border-color:#285b49}.evidence{font-size:12px;color:var(--faint);margin-top:9px}.edit{display:grid;grid-template-columns:120px 120px 120px 130px 1fr 120px auto;gap:8px;margin-top:15px;padding-top:14px;border-top:1px solid var(--line);align-items:end}.edit label{font-size:10px;color:var(--faint);display:grid;gap:5px}.edit select,.edit input{width:100%;background:#0f141b;color:var(--ink);border:1px solid var(--line);border-radius:7px;padding:8px;font-size:12px}.edit button{border:0;border-radius:8px;background:var(--acc);color:#17120a;font-weight:800;padding:9px 13px;cursor:pointer}.empty{padding:30px;border:1px solid var(--line);border-radius:14px;color:var(--mut)}@media(max-width:850px){.score{grid-template-columns:repeat(2,1fr)}.edit{grid-template-columns:repeat(2,1fr)}.edit .wide{grid-column:1/-1}.head{display:block}.flag{display:inline-block;margin-top:9px}}`;

export default async function OutreachPage({ searchParams }: { searchParams: Promise<{key?: string}> }) {
  const { key } = await searchParams;
  if (!(await isAdmin(key))) redirect("/admin/login?to=" + encodeURIComponent(HERE));
  const targets = await listOutreach();
  const count = (s: string) => targets.filter(t => t.status === s).length;
  return <main className="out"><style dangerouslySetInnerHTML={{__html:CSS}}/><div className="w">
    <div className="top"><div><div className="eyebrow">CITED · 첫 고객 영업</div><h1>학원 10곳 유치판</h1><div className="desc">공개 정보는 후보 선정용입니다. 세 조건을 통화로 확인한 곳에만 39만원 파일럿을 제안합니다.</div></div><Link className="back" href="/admin/ops">운영 현황으로 →</Link></div>
    <div className="score"><div><b>{targets.length}</b><span>후보</span></div><div><b>{count("조건 충족")}</b><span>대화·자격 확인</span></div><div><b>{count("제안 발송")}</b><span>제안</span></div><div><b>{count("결제")}</b><span>결제</span></div><div><b>{targets.filter(qualifies).length}</b><span>3조건 확인</span></div></div>
    <section className="today"><h2>오늘 당신이 할 일 — 위에서 3곳</h2><ol><li>전화해서 <strong>원장 연결</strong>을 요청합니다.</li><li>원장 직접 상담 · 월 문의 5건 이상 · 단일 지점, 세 가지만 확인합니다.</li><li>셋 다 맞으면 30일 유료 파일럿을 말하고 제안문을 보냅니다.</li><li>통화 직후 아래 상태와 다음 행동을 저장합니다.</li></ol><div className="script">“사이티드의 이재원입니다. 네이버 순위 광고가 아니라, 학부모가 ChatGPT나 AI 검색에 ‘이 지역 코딩학원’을 물었을 때 학원이 어떤 근거로 언급되는지 30일 동안 측정하고 고치는 일을 합니다. 성과 판정이 가능한 학원만 받고 있어서 두 가지만 여쭤보겠습니다. 원장님이 신규 상담을 직접 받으시나요? 최근 한 달 신규 문의가 대략 5건 이상인가요?”<br/><br/>조건 충족 시: “3곳만 39만원 유료 파일럿으로 진행합니다. 질문 20개를 두 번 기준 측정하고, 정보 정합성 수정안·근거 콘텐츠 1개·30일 재측정·상담 유입 기록표까지 드립니다. 노출이나 순위는 보장하지 않습니다. 결과가 없으면 실패 원인을 남기고 갱신 권유도 하지 않습니다.”</div></section>
    {targets.length === 0 ? <div className="empty">영업 후보 표가 아직 없습니다. <code>npm run setup-outreach</code>를 한 번 실행하세요.</div> : <div className="cards">{targets.map((t,i)=><article className="card" key={t.id}><div className="head"><div><div><span className="rank">#{i+1} · P{t.priority}</span><span className="name">{t.name}</span></div><div className="meta">{t.district} {t.neighborhood} · {t.address ?? "주소 추가 확인"} · {t.phone ?? "전화번호 추가 확인"}</div><div className="links">{t.phone && <a href={`tel:${t.phone}`}>전화</a>}{t.website && <a href={t.website} target="_blank">홈페이지</a>}<a href={t.evidenceUrl} target="_blank">선정 근거</a></div></div><span className={`flag ${qualifies(t)?"ok":""}`}>{qualifies(t)?"제안 가능":t.status}</span></div><div className="evidence">{t.evidenceNote}</div>
      <form className="edit" action={updateOutreach}><input type="hidden" name="id" value={t.id}/>{[["owner","원장 직접 상담",t.ownerConsults],["volume","월 문의 5건+",t.monthlyInquiries5plus],["single","단일 지점",t.singleLocation]].map(([n,l,v])=><label key={String(n)}>{String(l)}<select name={String(n)} defaultValue={yn(v as boolean|null)}><option value="unknown">미확인</option><option value="yes">예</option><option value="no">아니오</option></select></label>)}<label>상태<select name="status" defaultValue={t.status}>{OUTREACH_STATUSES.map(s=><option key={s}>{s}</option>)}</select></label><label className="wide">다음 행동<input name="next" defaultValue={t.nextAction}/></label><label>기한<input type="date" name="due" defaultValue={t.nextDue ?? ""}/></label><label className="wide">메모<input name="note" defaultValue={t.note}/></label><button>저장</button></form>
    </article>)}</div>}
  </div></main>;
}
